language: python

python:
    - "2.7"
    - "pypy"
    - "3.3"

before_install:
    - pip --quiet install coverage

install:
    - python setup.py --quiet install

script:
    - ./gccanalyze --verbose bad.cc
    - ./gccanalyze --verbose okay.cc
    - ./gccanalyze --verbose --strict-shadow okay.cc
    - python test_gccanalyze.py
    - coverage run test_gccanalyze.py
    - coverage report --show-missing
